package ar.jujuy.pov.modelo.dominio;
// Generated 03/12/2015 04:50:55 by Hibernate Tools 4.3.1

/**
 * Destino generated by hbm2java
 */
public class Destino  implements java.io.Serializable {


     private long idDestino;
     private String direccion;
     private String nombre;
     private boolean estado;

    public Destino(){
    }

    public long getIdDestino() {
        return this.idDestino;
    }
    
    public void setIdDestino(long idDestino) {
        this.idDestino = idDestino;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public boolean isEstado() {
        return estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    
}


