package ar.jujuy.pov.modelo.dominio;
// Generated 03/12/2015 04:50:55 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * DetalleEgreso generated by hbm2java
 */
public class DetalleEgreso  implements java.io.Serializable {


     private long idDetalleEgreso;
     private EncabezadoEgreso encabezadoEgreso;
     private Producto producto;
     private BigDecimal cantidad;

    public DetalleEgreso() {
    }

    public DetalleEgreso(long idDetalleEgreso, EncabezadoEgreso encabezadoEgreso, Producto producto, BigDecimal cantidad) {
       this.idDetalleEgreso = idDetalleEgreso;
       this.encabezadoEgreso = encabezadoEgreso;
       this.producto = producto;
       this.cantidad = cantidad;
    }
   
    public long getIdDetalleEgreso() {
        return this.idDetalleEgreso;
    }
    
    public void setIdDetalleEgreso(long idDetalleEgreso) {
        this.idDetalleEgreso = idDetalleEgreso;
    }
    public EncabezadoEgreso getEncabezadoEgreso() {
        return this.encabezadoEgreso;
    }
    
    public void setEncabezadoEgreso(EncabezadoEgreso encabezadoEgreso) {
        this.encabezadoEgreso = encabezadoEgreso;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
}


