package ar.jujuy.pov.modelo.dominio;
// Generated 03/12/2015 04:50:55 by Hibernate Tools 4.3.1

/**
 * DetalleUnidad generated by hbm2java
 */
public class DetalleUnidad  implements java.io.Serializable {


     private short idUnidad;
     private String descripcion;
     private String abreviatura;

    public DetalleUnidad() {
    }

    public short getIdUnidad() {
        return this.idUnidad;
    }
    
    public void setIdUnidad(short idUnidad) {
        this.idUnidad = idUnidad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getAbreviatura() {
        return abreviatura;
    }

    public void setAbreviatura(String abreviatura) {
        this.abreviatura = abreviatura;
    }
    
}


