package ar.jujuy.pov.modelo.dominio;
// Generated 03/12/2015 04:50:55 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * EncabezadoIngreso generated by hbm2java
 */
public class EncabezadoIngreso  implements java.io.Serializable {


     private long idIngreso;
     private Destino destino;
     private Proveedor proveedor;
     private Usuario usuario;
     private Date fechaCreacion;
     private Date fechaCompra;
     private String numeroFactura;
     private String numeroRecibo;
     private String numeroOrden;
     private int encargadoDepositoId;
     private int encargadoResponsableId;

    public EncabezadoIngreso() {
    }
	
    public long getIdIngreso() {
        return this.idIngreso;
    }
    
    public void setIdIngreso(long idIngreso) {
        this.idIngreso = idIngreso;
    }
    public Destino getDestino() {
        return this.destino;
    }
    
    public void setDestino(Destino destino) {
        this.destino = destino;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
    public String getNumeroFactura() {
        return this.numeroFactura;
    }
    
    public void setNumeroFactura(String numeroFactura) {
        this.numeroFactura = numeroFactura;
    }
    public String getNumeroRecibo() {
        return this.numeroRecibo;
    }
    
    public void setNumeroRecibo(String numeroRecibo) {
        this.numeroRecibo = numeroRecibo;
    }
    public String getNumeroOrden() {
        return this.numeroOrden;
    }
    
    public void setNumeroOrden(String numeroOrden) {
        this.numeroOrden = numeroOrden;
    }
    public int getEncargadoDepositoId() {
        return this.encargadoDepositoId;
    }
    
    public void setEncargadoDepositoId(int encargadoDepositoId) {
        this.encargadoDepositoId = encargadoDepositoId;
    }
    public int getEncargadoResponsableId() {
        return this.encargadoResponsableId;
    }

    public void setEncargadoResponsableId(int encargadoResponsableId) {
        this.encargadoResponsableId = encargadoResponsableId;
    }

    
}


