package ar.jujuy.pov.modelo.dominio;
// Generated 03/12/2015 04:50:55 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private long idProducto;
     private DetalleUnidad detalleUnidad;
     private Marca marca;
     private TipoProducto tipoProducto;
     private String descripcion;
     private String imagen;
     private BigDecimal stock;
     private boolean estado;
     

    public Producto() {
    }

    public long getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(long idProducto) {
        this.idProducto = idProducto;
    }
    public DetalleUnidad getDetalleUnidad() {
        return this.detalleUnidad;
    }
    
    public void setDetalleUnidad(DetalleUnidad detalleUnidad) {
        this.detalleUnidad = detalleUnidad;
    }
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    public TipoProducto getTipoProducto() {
        return this.tipoProducto;
    }
    
    public void setTipoProducto(TipoProducto tipoProducto) {
        this.tipoProducto = tipoProducto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public BigDecimal getStock() {
        return this.stock;
    }
    
    public void setStock(BigDecimal stock) {
        this.stock = stock;
    }

    public boolean isEstado() {
        return estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    
    public String codigoGenerado(long id){
        String cod ="P-0000000000000000000";
        String num=String.valueOf(id);
        cod=cod.substring(0, cod.length()-num.length())+num;
        System.out.println(cod);
        return cod;
    }

}


