package ar.jujuy.pov.modelo.dominio;
// Generated 03/12/2015 04:50:55 by Hibernate Tools 4.3.1

/**
 * TipoProducto generated by hbm2java
 */
public class TipoProducto implements java.io.Serializable {

    private short idTipoProducto;
    private String descripcion;
    private boolean estado;

    public TipoProducto() {
    }

    public short getIdTipoProducto() {
        return this.idTipoProducto;
    }

    public void setIdTipoProducto(short idTipoProducto) {
        this.idTipoProducto = idTipoProducto;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public boolean isEstado() {
        return estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

}
